title : Shaked Meir 
logo: /assets/img/mypicture.png
description: Student for B.Sc of Electrical & Electronic Engineering
show_downloads: true
theme: minima
header_pages:
  - about.md
  - portfolio.md
    social_links:
   - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
